import fs from 'fs-extra';
import path from 'path';

export async function generateMarkdown(documentation, outputPath) {
  await fs.ensureDir(outputPath);
  
  // Generate main README.md
  const mainReadme = generateMainReadme(documentation);
  await fs.writeFile(path.join(outputPath, 'README.md'), mainReadme);
  
  // Generate individual level documents
  if (documentation.levels.context) {
    const contextDoc = generateContextDoc(documentation.levels.context, documentation);
    await fs.writeFile(path.join(outputPath, '01-context-diagram.md'), contextDoc);
  }
  
  if (documentation.levels.container) {
    const containerDoc = generateContainerDoc(documentation.levels.container, documentation);
    await fs.writeFile(path.join(outputPath, '02-container-diagram.md'), containerDoc);
  }
  
  if (documentation.levels.component) {
    const componentDoc = generateComponentDoc(documentation.levels.component, documentation);
    await fs.writeFile(path.join(outputPath, '03-component-diagram.md'), componentDoc);
  }
  
  if (documentation.levels.code) {
    const codeDoc = generateCodeDoc(documentation.levels.code, documentation);
    await fs.writeFile(path.join(outputPath, '04-code-diagram.md'), codeDoc);
  }
  
  // Generate mermaid diagrams
  await generateMermaidDiagrams(documentation, outputPath);
}

function generateMainReadme(doc) {
  const { projectName, generatedAt, levels } = doc;
  
  return `# 🏗️ ${projectName} - System Architecture Documentation

> **Project Name:** ${projectName}  
> **Document Version:** 1.0  
> **Generated At:** ${new Date(generatedAt).toLocaleString('vi-VN')}  
> **Generated By:** [c4-gen](https://github.com/haodq4/c4-gen) - AI-Powered C4 Model Documentation Generator

---

## 📑 TABLE OF CONTENTS

### 📐 Architecture Overview
1. [Overview](#1-overview)
2. [System Context Diagram (C4 Level 1)](#2-system-context-diagram-c4-level-1)
3. [Container Diagram (C4 Level 2)](#3-container-diagram-c4-level-2)
4. [Component Diagram (C4 Level 3)](#4-component-diagram-c4-level-3)
5. [Code Diagram (C4 Level 4)](#5-code-diagram-c4-level-4)

### 🛠️ Technology & Infrastructure
6. [Technology Stack](#6-technology-stack)
7. [Infrastructure Architecture](#7-infrastructure-architecture)
8. [Database Architecture](#8-database-architecture)
9. [Security Architecture](#9-security-architecture)

### � Documentation Links
${levels.context ? '- [✅ Level 1: Context Diagram](./01-context-diagram.md) - System Overview & External Integrations' : ''}
${levels.container ? '- [✅ Level 2: Container Diagram](./02-container-diagram.md) - Containers & Technology Stack' : ''}
${levels.component ? '- [✅ Level 3: Component Diagram](./03-component-diagram.md) - Internal Components & APIs' : ''}
${levels.code ? '- [✅ Level 4: Code Diagram](./04-code-diagram.md) - Sequence Diagrams & Class Details' : ''}

---

## 1. Overview

### 1.1 What is C4 Model?

The C4 model is a lean graphical notation technique for modelling software architecture. It consists of 4 levels:

\`\`\`
┌─────────────────────────────────────────────────────────────────────────┐
│                          C4 MODEL HIERARCHY                             │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                         │
│   Level 1: System Context    → Big picture (System + Users + External) │
│   Level 2: Container         → Containers (Apps, DBs, Services)        │
│   Level 3: Component         → Components (Controllers, Services...)   │
│   Level 4: Code              → Sequence Diagrams & Class Details       │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
\`\`\`

### 1.2 How to Read This Documentation

1. **Start with Context** - Understand the big picture
2. **Explore Containers** - See the main building blocks
3. **Dive into Components** - Understand internal structure
4. **Review Code Details** - See implementation specifics

---

## 2. System Context Diagram (C4 Level 1)

${levels.context ? '→ [View Detailed Context Diagram](./01-context-diagram.md)' : ''}

${levels.context ? generateContextSummary(levels.context) : 'Context diagram not generated.'}

---

## 3. Container Diagram (C4 Level 2)

${levels.container ? '→ [View Detailed Container Diagram](./02-container-diagram.md)' : ''}

${levels.container ? generateContainerSummary(levels.container) : 'Container diagram not generated.'}

---

## 4. Component Diagram (C4 Level 3)

${levels.component ? '→ [View Detailed Component Diagram](./03-component-diagram.md)' : ''}

${levels.component ? generateComponentSummary(levels.component) : 'Component diagram not generated.'}

---

## 5. Code Diagram (C4 Level 4)

${levels.code ? '→ [View Detailed Code Diagram](./04-code-diagram.md)' : ''}

${levels.code ? generateCodeSummary(levels.code) : 'Code diagram not generated.'}

---

## 6. Technology Stack

${levels.context?.technologies || levels.container ? generateTechnologyStack(levels) : 'Technology stack information not available.'}

---

## 7. Infrastructure Architecture

${levels.container ? generateInfrastructureSummary(levels.container) : 'Infrastructure details not available.'}

---

## 8. Database Architecture

${levels.code?.databaseSchema ? generateDatabaseSummary(levels.code.databaseSchema) : 'Database schema not available.'}

---

## 9. Security Architecture

${levels.context?.externalSystems ? generateSecuritySummary(levels.context) : 'Security information not available.'}

---

## 📚 References

- [C4 Model Official Site](https://c4model.com/)
- [Mermaid Documentation](https://mermaid.js.org/)
- [c4-gen Tool](https://github.com/haodq4/c4-gen)

---

**Generated by c4-gen** - AI-Powered Architecture Documentation Tool
`;
}

// Helper functions for summaries
function generateContextSummary(context) {
  return `
### System: ${context.systemName || 'Unknown'}

**Description:** ${context.description || 'No description'}

**Key Users:** ${context.users?.map(u => u.name).join(', ') || 'None'}

**External Systems:** ${context.externalSystems?.map(s => s.name).join(', ') || 'None'}

**Architecture Style:** ${context.architectureStyle || 'Not specified'}
`;
}

function generateContainerSummary(container) {
  const containers = container.containers || [];
  return `
### Main Containers

${containers.slice(0, 5).map(c => `
- **${c.name}** (${c.type})
  - Technology: ${c.technology}
  - ${c.description}
`).join('\n')}

${containers.length > 5 ? `\n*...and ${containers.length - 5} more containers*` : ''}
`;
}

function generateComponentSummary(component) {
  const components = component.components || [];
  return `
### Main Components

${components.slice(0, 5).map(c => `
- **${c.name}** (${c.type})
  - ${c.description}
`).join('\n')}

${components.length > 5 ? `\n*...and ${components.length - 5} more components*` : ''}
`;
}

function generateCodeSummary(code) {
  const sequences = code.sequenceDiagrams || [];
  const classes = code.classes || [];
  return `
### Sequence Diagrams: ${sequences.length}

${sequences.slice(0, 3).map(s => `- ${s.name}`).join('\n')}

### Classes/Interfaces: ${classes.length}

${classes.slice(0, 5).map(c => `- ${c.name} (${c.type})`).join('\n')}
`;
}

function generateTechnologyStack(levels) {
  const tech = levels.context?.technologies || {};
  return `
| Layer | Technologies |
|-------|-------------|
| Frontend | ${tech.frontend?.join(', ') || 'Not specified'} |
| Backend | ${tech.backend?.join(', ') || 'Not specified'} |
| Database | ${tech.database?.join(', ') || 'Not specified'} |
| Infrastructure | ${tech.infrastructure?.join(', ') || 'Not specified'} |
`;
}

function generateInfrastructureSummary(container) {
  const infra = container.infrastructureComponents || [];
  return infra.length > 0 ? `
${infra.map(i => `- **${i.name}**: ${i.technology} - ${i.purpose}`).join('\n')}
` : 'No infrastructure components documented.';
}

function generateDatabaseSummary(schema) {
  const tables = schema.tables || [];
  return `
### Database Tables: ${tables.length}

${tables.slice(0, 5).map(t => `- **${t.name}**: ${t.description || 'No description'}`).join('\n')}

${tables.length > 5 ? `*...and ${tables.length - 5} more tables*` : ''}
`;
}

function generateSecuritySummary(context) {
  const authSystems = context.externalSystems?.filter(s => 
    s.category?.toLowerCase().includes('auth') || 
    s.name?.toLowerCase().includes('auth')
  ) || [];
  
  return authSystems.length > 0 ? `
### Authentication & Authorization

${authSystems.map(s => `- **${s.name}**: ${s.description}`).join('\n')}
` : 'Authentication details not documented.';
}

function generateContextDoc(context, doc) {
  return `# C4 Level 1: System Context Diagram

## ${context.systemName || doc.projectName}

> **Architecture Style:** ${context.architectureStyle || 'Not specified'}  
> **Deployment Model:** ${context.deploymentModel || 'Not specified'}

---

## 1. Business Context

**Description:** ${context.description || 'No description available'}

**Purpose:** ${context.purpose || 'Not specified'}

**Business Context:** ${context.businessContext || 'Not specified'}

---

## 2. Stakeholders

${context.stakeholders?.map(stakeholder => `
### ${stakeholder.role}

- **Description:** ${stakeholder.description}
- **Concerns:** ${stakeholder.concerns}
`).join('\n') || 'No stakeholder information available'}

---

## 3. System Users & Actors

${context.users?.map(user => `
### 👤 ${user.name} (${user.type || 'User'})

**Description:** ${user.description}

**Access:** ${user.access || 'Not specified'}

**Interactions:**
${user.interactions?.map(i => `- ${i}`).join('\n') || '- No interactions documented'}
`).join('\n') || 'No user information available'}

---

## 4. External Systems & Integrations

${context.externalSystems?.map(sys => `
### 🔌 ${sys.name}

| Property | Value |
|----------|-------|
| **Category** | ${sys.category || 'Not specified'} |
| **Protocol** | ${sys.protocol || 'Not specified'} |
| **Direction** | ${sys.direction || 'Not specified'} |
| **Purpose** | ${sys.purpose || 'Not specified'} |

**Description:** ${sys.description || 'No description'}

**Data Flow:** ${sys.dataFlow || 'Not specified'}
`).join('\n---\n') || 'No external systems documented'}

---

## 5. System Context Diagram

\`\`\`mermaid
graph TB
    ${generateContextMermaid(context)}
\`\`\`

---

## 6. Communication Protocols

${generateProtocolsTable(context)}

---

## 7. Architecture Principles

${context.keyPrinciples?.map((principle, index) => `${index + 1}. ${principle}`).join('\n') || 'No principles documented'}

---

## 8. Technology Overview

${generateTechOverview(context.technologies)}

---

[← Back to Main](./README.md) | [Next: Container Diagram →](./02-container-diagram.md)
`;
}

function generateContextMermaid(context) {
  const users = context.users || [];
  const externalSystems = context.externalSystems || [];
  const systemName = context.systemName || 'System';
  
  let mermaid = `
    User1[👤 Users] --> System[${systemName}]
    ${externalSystems.map((sys, i) => `
    System --> Ext${i}[${sys.name}]`).join('')}
  `;
  
  return mermaid;
}

function generateProtocolsTable(context) {
  const systems = context.externalSystems || [];
  if (systems.length === 0) return 'No protocols documented';
  
  return `
| Connection | Protocol | Direction | Description |
|------------|----------|-----------|-------------|
${systems.map(s => `| ${s.name} | ${s.protocol || 'HTTP'} | ${s.direction || 'Outbound'} | ${s.purpose || 'Integration'} |`).join('\n')}
`;
}

function generateTechOverview(technologies) {
  if (!technologies) return 'No technology information available';
  
  return `
| Layer | Technologies |
|-------|-------------|
${technologies.frontend ? `| **Frontend** | ${technologies.frontend.join(', ')} |` : ''}
${technologies.backend ? `| **Backend** | ${technologies.backend.join(', ')} |` : ''}
${technologies.database ? `| **Database** | ${technologies.database.join(', ')} |` : ''}
${technologies.infrastructure ? `| **Infrastructure** | ${technologies.infrastructure.join(', ')} |` : ''}
`;
}

function generateContainerDoc(container, doc) {
  return `# C4 Level 2: Container Diagram

## Architecture Style

**Style:** ${container.architectureStyle || 'Not specified'}

---

## 1. Containers Overview

${container.containers?.map((c, index) => `
### ${index + 1}. ${c.name}

| Property | Value |
|----------|-------|
| **Type** | ${c.type} |
| **Technology** | ${c.technology} |
| **Port** | ${c.port || 'N/A'} |
| **Replicas** | ${c.replicas || '1'} |
| **Resources** | ${c.resources ? `${c.resources.memory} / ${c.resources.cpu} CPU` : 'Not specified'} |
| **Protocols** | ${c.protocols?.join(', ') || 'Not specified'} |

**Description:** ${c.description}

#### Responsibilities:
${c.responsibilities?.map(r => `- ${r}`).join('\n') || '- No responsibilities documented'}

#### Key Endpoints:
${c.endpoints?.map(e => `- \`${e}\``).join('\n') || '- No endpoints documented'}

#### Dependencies:
${c.dependencies?.map(d => `- ${d}`).join('\n') || '- No dependencies'}

#### Interactions:
${c.interactions?.map(i => `
- **To:** ${i.to}
  - **Protocol:** ${i.protocol}
  - **Direction:** ${i.direction}
  - **Type:** ${i.isAsync ? 'Async' : 'Sync'}
  - **Description:** ${i.description}
  - **Data:** ${i.dataExchanged || 'Not specified'}
`).join('\n') || '- No interactions documented'}

---
`).join('\n') || 'No containers documented'}

## 2. Data Stores

${container.dataStores?.map(ds => `
### 💾 ${ds.name}

| Property | Value |
|----------|-------|
| **Type** | ${ds.type} |
| **Technology** | ${ds.technology} |
| **Data Model** | ${ds.dataModel || 'Not specified'} |
| **Port** | ${ds.port || 'N/A'} |

**Purpose:** ${ds.purpose}
`).join('\n') || 'No data stores documented'}

---

## 3. Messaging Layer

${container.messagingLayer ? `
**Technology:** ${container.messagingLayer.technology}

**Purpose:** ${container.messagingLayer.purpose}

**Queues:**
${container.messagingLayer.queues?.map(q => `- ${q}`).join('\n') || '- None'}
` : 'No messaging layer documented'}

---

## 4. Infrastructure Components

${container.infrastructureComponents?.map(ic => `
### ${ic.name}

- **Technology:** ${ic.technology}
- **Purpose:** ${ic.purpose}
`).join('\n') || 'No infrastructure components documented'}

---

## 5. Container Diagram

\`\`\`mermaid
graph TB
    ${generateContainerMermaid(container)}
\`\`\`

---

## 6. Container Specifications

| Container | Technology | Port | Replicas | Memory | CPU | Storage |
|-----------|------------|------|----------|--------|-----|---------|
${container.containers?.map(c => `| ${c.name} | ${c.technology} | ${c.port || '-'} | ${c.replicas || '1'} | ${c.resources?.memory || '-'} | ${c.resources?.cpu || '-'} | ${c.storage || '-'} |`).join('\n') || ''}

---

[← Back: Context Diagram](./01-context-diagram.md) | [Main](./README.md) | [Next: Component Diagram →](./03-component-diagram.md)
`;
}

function generateContainerMermaid(container) {
  const containers = container.containers || [];
  const dataStores = container.dataStores || [];
  
  let mermaid = containers.map((c, i) => `C${i}[${c.name}]`).join('\n    ');
  mermaid += '\n    ' + dataStores.map((ds, i) => `DB${i}[(${ds.name})]`).join('\n    ');
  
  // Add interactions
  containers.forEach((c, i) => {
    c.interactions?.forEach(inter => {
      const targetIndex = containers.findIndex(t => t.name === inter.to);
      if (targetIndex >= 0) {
        mermaid += `\n    C${i} -->|${inter.protocol}| C${targetIndex}`;
      }
    });
  });
  
  return mermaid;
}

function generateComponentDoc(component, doc) {
  return `# C4 Level 3: Component Diagram

## Architecture Layers

${component.architectureLayers?.map(layer => `
### ${layer.name}

**Purpose:** ${layer.purpose}

**Components:** ${layer.components?.join(', ') || 'None'}
`).join('\n') || 'No architecture layers documented'}

---

## 1. Components

${component.components?.map((c, index) => `
### ${index + 1}. ${c.name}

| Property | Value |
|----------|-------|
| **Type** | ${c.type} |
| **Layer** | ${c.layer || 'Not specified'} |
| **Technology** | ${c.technology} |

**Description:** ${c.description}

#### Responsibilities:
${c.responsibilities?.map(r => `- ${r}`).join('\n') || '- No responsibilities'}

#### Source Files:
${c.files?.map(f => `- \`${f}\``).join('\n') || '- No files documented'}

#### API Endpoints:
${c.apiEndpoints?.map(ep => `
- **${ep.method}** \`${ep.path}\`
  - Description: ${ep.description}
  - Auth: ${ep.authentication}
  - Authorization: ${ep.authorization}
`).join('\n') || '- No endpoints'}

#### Dependencies:
${c.dependencies?.map(d => `- **${d.component}** (${d.type}) - ${d.purpose}`).join('\n') || '- No dependencies'}

#### Design Patterns:
${c.designPatterns?.map(p => `- ${p}`).join('\n') || '- None'}

#### Key Methods:
${c.methods?.map(m => `
- \`${m.name}(${m.parameters?.join(', ') || ''})\` → ${m.returnType}
  - ${m.purpose}
`).join('\n') || '- No methods documented'}

---
`).join('\n') || 'No components documented'}

## 2. Middleware Chain

${component.middlewareChain?.map((mw, index) => `
${index + 1}. **${mw.name}** (Order: ${mw.order})
   - Purpose: ${mw.purpose}
   - Applies to: ${mw.appliesTo}
`).join('\n') || 'No middleware chain documented'}

---

## 3. Data Flow

${component.dataFlow ? `
**Request Flow:** ${component.dataFlow.requestFlow}

**Response Flow:** ${component.dataFlow.responseFlow}
` : 'No data flow documented'}

---

## 4. Cross-Cutting Concerns

${component.crossCuttingConcerns?.map(concern => `
### ${concern.name}

- **Implementation:** ${concern.implementation}
- **Components:** ${concern.components?.join(', ') || 'None'}
`).join('\n') || 'No cross-cutting concerns documented'}

---

## 5. Component Diagram

\`\`\`mermaid
graph TB
    ${generateComponentMermaid(component)}
\`\`\`

---

[← Back: Container Diagram](./02-container-diagram.md) | [Main](./README.md) | [Next: Code Diagram →](./04-code-diagram.md)
`;
}

function generateComponentMermaid(component) {
  const components = component.components || [];
  let mermaid = components.map((c, i) => `Comp${i}[${c.name}\\n${c.type}]`).join('\n    ');
  
  // Add dependencies
  components.forEach((c, i) => {
    c.dependencies?.forEach(dep => {
      const targetIndex = components.findIndex(t => t.name === dep.component);
      if (targetIndex >= 0) {
        mermaid += `\n    Comp${i} -->|${dep.type}| Comp${targetIndex}`;
      }
    });
  });
  
  return mermaid;
}

function generateCodeDoc(code, doc) {
  return `# C4 Level 4: Code Diagram (Sequence Diagrams & Implementation Details)

## 1. Sequence Diagrams

${code.sequenceDiagrams?.map((seq, index) => `
### ${index + 1}. ${seq.name}

**Description:** ${seq.description}

**Actors:** ${seq.actors?.join(', ') || 'Not specified'}

#### Flow Steps:

${seq.steps?.map((step, stepIndex) => `
${stepIndex + 1}. **${step.from}** → **${step.to}**
   - Action: \`${step.action}\`
   - Description: ${step.description}
   - Data: \`${step.dataExchanged || 'N/A'}\`
   - Response: ${step.responseType}
   ${step.conditions ? `- Conditions: ${step.conditions}` : ''}
`).join('\n') || 'No steps documented'}

${seq.alternativeFlows?.length > 0 ? `
#### Alternative Flows:

${seq.alternativeFlows.map(alt => `
**Condition:** ${alt.condition}

Steps:
${alt.steps?.map((s, i) => `${i + 1}. ${s}`).join('\n') || '- None'}
`).join('\n')}
` : ''}

#### Sequence Diagram:

\`\`\`mermaid
${seq.mermaidCode || generateSequenceMermaid(seq)}
\`\`\`

---
`).join('\n') || 'No sequence diagrams documented'}

---

## 2. Class Diagrams & Details

${code.classes?.map((cls, index) => {
  if (!cls || !cls.name) return '';
  return `
### ${index + 1}. ${cls.name}

| Property | Value |
|----------|-------|
| **Type** | ${cls.type || 'class'} |
| **File** | \`${cls.file || 'Not specified'}\` |
| **Extends** | ${cls.extends || 'None'} |
| **Implements** | ${cls.implements?.join(', ') || 'None'} |

**Description:** ${cls.description || 'No description'}

#### Design Patterns:
${cls.designPatterns?.map(p => `- ${p}`).join('\n') || '- None'}

#### Properties:

${cls.properties?.map(prop => {
  if (!prop || !prop.name) return '';
  return `
- **\`${prop.name}\`** (${prop.type || 'any'})
  - Visibility: ${prop.visibility || 'public'}
  - Required: ${prop.isRequired ? 'Yes' : 'No'}
  ${prop.defaultValue ? `- Default: \`${prop.defaultValue}\`` : ''}
  - Description: ${prop.description || 'N/A'}
`;
}).filter(p => p).join('\n') || '- No properties'}

#### Methods:

${cls.methods?.map(method => {
  if (!method || !method.name) return '';
  return `
##### \`${method.name}(${method.parameters?.map(p => `${p.name || 'param'}: ${p.type || 'any'}`).join(', ') || ''})\`

- **Visibility:** ${method.visibility || 'public'}
- **Static:** ${method.isStatic ? 'Yes' : 'No'}
- **Async:** ${method.isAsync ? 'Yes' : 'No'}
- **Returns:** ${method.returnType || 'void'}
- **Description:** ${method.description || 'N/A'}

${method.parameters?.length > 0 ? `**Parameters:**
${method.parameters.map(p => `- \`${p.name || 'param'}\` (${p.type || 'any'}) ${p.isOptional ? '[Optional]' : '[Required]'}: ${p.description || 'N/A'}`).join('\n')}
` : ''}

${method.exceptions?.length > 0 ? `**Exceptions:** ${method.exceptions.join(', ')}` : ''}
`;
}).filter(m => m).join('\n') || '- No methods'}

#### Relationships:

${cls.relationships?.map(rel => {
  if (!rel || !rel.type || !rel.to) return '';
  return `
- **${rel.type}** → **${rel.to}**
  - Description: ${rel.description || 'N/A'}
  - Cardinality: ${rel.cardinality || 'Not specified'}
`;
}).filter(r => r).join('\n') || '- No relationships'}

---
`;
}).filter(c => c).join('\n') || 'No classes documented'}

---

## 3. Database Schema

${code.databaseSchema ? generateDatabaseSchemaDoc(code.databaseSchema) : 'No database schema documented'}

---

## 4. Data Flow

**Overview:** ${code.dataFlow || 'Not documented'}

---

## 5. Key Business Flows

${code.keyBusinessFlows?.map((flow, index) => `
### ${index + 1}. ${flow.name}

**Description:** ${flow.description}

**Steps:**
${flow.steps?.map((s, i) => `${i + 1}. ${s}`).join('\n') || '- No steps'}

**Involved Components:**
${flow.involvedComponents?.map(c => `- ${c}`).join('\n') || '- None'}
`).join('\n') || 'No business flows documented'}

---

## 6. Complete Class Diagram

\`\`\`mermaid
classDiagram
${generateClassMermaid(code)}
\`\`\`

---

[← Back: Component Diagram](./03-component-diagram.md) | [Main](./README.md)
`;
}

function generateSequenceMermaid(seq) {
  if (!seq || !seq.steps || !Array.isArray(seq.steps)) {
    return 'sequenceDiagram\n    Note: No steps defined\n';
  }
  
  let mermaid = 'sequenceDiagram\n';
  seq.steps?.forEach(step => {
    if (!step || !step.from || !step.to || !step.action) return;
    mermaid += `    ${step.from}->>+${step.to}: ${step.action}\n`;
    if (step.responseType) {
      mermaid += `    ${step.to}-->>-${step.from}: ${step.responseType}\n`;
    }
  });
  return mermaid;
}

function generateClassMermaid(code) {
  const classes = code.classes || [];
  return classes.map(cls => {
    // Safe check for class name
    if (!cls || !cls.name) return '';
    
    const className = cls.name.replace(/[^a-zA-Z0-9]/g, '_');
    let mermaid = `    class ${className} {\n`;
    
    // Properties
    cls.properties?.forEach(prop => {
      if (!prop || !prop.name || !prop.type) return;
      const visibility = prop.visibility === 'private' ? '-' : prop.visibility === 'protected' ? '#' : '+';
      mermaid += `        ${visibility}${prop.type} ${prop.name}\n`;
    });
    
    // Methods
    cls.methods?.forEach(method => {
      if (!method || !method.name) return;
      const visibility = method.visibility === 'private' ? '-' : method.visibility === 'protected' ? '#' : '+';
      const params = method.parameters?.map(p => `${p.name}: ${p.type}`).join(', ') || '';
      mermaid += `        ${visibility}${method.name}(${params}) ${method.returnType || 'void'}\n`;
    });
    
    mermaid += '    }\n';
    
    // Relationships
    cls.relationships?.forEach(rel => {
      if (!rel || !rel.to || !rel.type) return;
      const target = rel.to.replace(/[^a-zA-Z0-9]/g, '_');
      if (rel.type === 'extends') {
        mermaid += `    ${target} <|-- ${className}\n`;
      } else if (rel.type === 'implements') {
        mermaid += `    ${target} <|.. ${className}\n`;
      } else if (rel.type === 'has-a' || rel.type === 'uses') {
        mermaid += `    ${className} --> ${target}\n`;
      }
    });
    
    return mermaid;
  }).filter(m => m).join('\n'); // Filter out empty strings
}

function generateDatabaseSchemaDoc(schema) {
  const tables = schema.tables || [];
  
  return `
### Database Tables

${tables.map((table, index) => `
#### ${index + 1}. ${table.name}

**Description:** ${table.description}

**Columns:**

| Column | Type | PK | FK | Nullable | Unique | Default |
|--------|------|----|----|----------|--------|---------|
${table.columns?.map(col => `| ${col.name} | ${col.type} | ${col.isPrimaryKey ? '✓' : ''} | ${col.isForeignKey ? '✓' : ''} | ${col.isNullable ? 'Yes' : 'No'} | ${col.isUnique ? '✓' : ''} | ${col.defaultValue || '-'} |`).join('\n') || ''}

${table.columns?.filter(col => col.references).length > 0 ? `
**Foreign Keys:**
${table.columns.filter(col => col.references).map(col => `
- \`${col.name}\` → \`${col.references.table}.${col.references.column}\`
  - On Delete: ${col.references.onDelete}
  - On Update: ${col.references.onUpdate}
`).join('\n')}
` : ''}

${table.indexes?.length > 0 ? `
**Indexes:**
${table.indexes.map(idx => `- ${idx.name} (${idx.columns.join(', ')}) ${idx.isUnique ? '[Unique]' : ''} [${idx.type}]`).join('\n')}
` : ''}

${table.relationships?.length > 0 ? `
**Relationships:**
${table.relationships.map(rel => `- ${rel.type} with \`${rel.with}\` via \`${rel.foreignKey}\` - ${rel.description}`).join('\n')}
` : ''}
`).join('\n---\n')}

### Entity Relationship Diagram

\`\`\`mermaid
${schema.erdDiagram || generateERDMermaid(schema)}
\`\`\`
`;
}

function generateERDMermaid(schema) {
  const tables = schema.tables || [];
  let erd = 'erDiagram\n';
  
  tables.forEach(table => {
    table.relationships?.forEach(rel => {
      const cardinality = rel.type === 'one-to-many' ? '||--o{' : 
                         rel.type === 'many-to-one' ? '}o--||' :
                         rel.type === 'many-to-many' ? '}o--o{' : '||--||';
      erd += `    ${table.name} ${cardinality} ${rel.with} : "${rel.description || 'relates'}"\n`;
    });
  });
  
  return erd;
}

async function generateMermaidDiagrams(documentation, outputPath) {
  // Tạo file riêng cho các diagram có thể render
  const diagramsPath = path.join(outputPath, 'diagrams');
  await fs.ensureDir(diagramsPath);
  
  // Các diagram đã được nhúng trong các file markdown
  // File này chỉ để tham khảo
  const diagramIndex = `# Mermaid Diagrams

Tất cả các diagram đã được tích hợp trong các file markdown tương ứng.

Bạn có thể xem chúng trực tiếp trên GitHub hoặc các Markdown viewer hỗ trợ Mermaid.

## Tools để xem Mermaid Diagrams:

- GitHub (hỗ trợ sẵn)
- VS Code với extension "Markdown Preview Mermaid Support"
- [Mermaid Live Editor](https://mermaid.live)
`;
  
  await fs.writeFile(path.join(diagramsPath, 'README.md'), diagramIndex);
}
